In [1]:
'''notebook to check if our matrices yield the correct results'''

from pbmo.lib.pymatrix import pyMatrix, npMatrix, cpMatrix
from pbmo.lib._libpbmo import Matrix, BoostMatrix
import numpy as np

In [2]:
# initalize
arr = np.random.rand(5, 5).astype(np.float32)

pymatrix = pyMatrix(arr)
npmatrix = npMatrix(arr)
cpmatrix = cpMatrix(arr)
cppmatrix = Matrix(arr)
boostmatrix = BoostMatrix(arr)

# check norm values
print(pymatrix.norm(), npmatrix.norm(), cpmatrix.norm(), cppmatrix.norm(), boostmatrix.norm())

# check matrix multiplication values
arr1 = np.random.rand(5, 5).astype(np.float32)

pymatrix1 = pyMatrix(arr1)
npmatrix1 = npMatrix(arr1)
cpmatrix1 = cpMatrix(arr1)
cppmatrix1 = Matrix(arr1)
boostmatrix1 = BoostMatrix(arr1)

# boostmatrix1.print_mat()

result_cpp = cppmatrix.matmul(cppmatrix1),
# print(result_cpp.rows)
result_boost = boostmatrix.matmul(boostmatrix1)
print(result_boost.rows)

print(
    pymatrix.matmul(pymatrix1).arr,
    "\n",
    npmatrix.matmul(npmatrix1).arr,
    "\n",
    cpmatrix.matmul(cpmatrix1).arr,
    "\n"
)

# cppmatrix.matmul(cppmatrix1).print_mat()
# boostmatrix.matmul(boostmatrix1).print_mat()

3.297302975379221 3.297303 3.297303 3.2973031997680664 3.2973031997680664
5
[[1.66347158 1.25073772 1.33364027 1.40273008 2.10692351]
 [1.6386881  0.95600065 1.1638297  1.26700696 2.0487049 ]
 [1.30722513 0.74059902 1.08056299 1.13254857 1.43418583]
 [1.50115429 0.93427895 0.86248799 1.3917883  1.44282055]
 [1.44306336 0.88241352 1.14840059 1.19600505 1.71519232]] 
 [[1.6634716 1.2507377 1.3336402 1.4027302 2.1069236]
 [1.6386881 0.9560007 1.1638297 1.267007  2.0487049]
 [1.3072251 0.740599  1.080563  1.1325486 1.4341859]
 [1.5011543 0.9342789 0.862488  1.3917882 1.4428205]
 [1.4430634 0.8824135 1.1484005 1.1960051 1.7151924]] 
 [[1.6634717  1.2507378  1.3336402  1.40273    2.1069236 ]
 [1.6386881  0.9560007  1.1638297  1.267007   2.048705  ]
 [1.3072251  0.74059904 1.0805631  1.1325486  1.4341857 ]
 [1.5011543  0.93427896 0.862488   1.3917884  1.4428205 ]
 [1.4430634  0.8824135  1.1484005  1.1960051  1.7151923 ]] 

