In [1]:
'''notebook to check if our matrices yield the correct results'''

from pbmo.lib.pymatrix import pyMatrix, npMatrix, cpMatrix
from pbmo.lib._libpbmo import Matrix, BoostMatrix
import numpy as np

In [3]:
# initalize
arr = np.random.rand(5, 5).astype(np.float32)

pymatrix = pyMatrix(arr)
npmatrix = npMatrix(arr)
cpmatrix = cpMatrix(arr)
cppmatrix = Matrix(arr)
boostmatrix = BoostMatrix(arr)

# check norm values
print(pymatrix.norm(), npmatrix.norm(), cpmatrix.norm(), cppmatrix.norm(), boostmatrix.norm())

# check matrix multiplication values
arr1 = np.random.rand(5, 5).astype(np.float32)

pymatrix1 = pyMatrix(arr1)
npmatrix1 = npMatrix(arr1)
cpmatrix1 = cpMatrix(arr1)
cppmatrix1 = Matrix(arr1)
boostmatrix1 = BoostMatrix(arr1)

# boostmatrix1.print_mat()

result_cpp = cppmatrix.matmul(cppmatrix1),
# print(result_cpp.rows)
result_boost = boostmatrix.matmul(boostmatrix1)
print(result_boost.rows)

print(
    pymatrix.matmul(pymatrix1)[0],
    "\n",
    npmatrix.matmul(npmatrix1)[0],
    "\n",
    cpmatrix.matmul(cpmatrix1)[0],
    "\n"
)

cppmatrix.matmul(cppmatrix1).print_mat()
boostmatrix.matmul(boostmatrix1).print_mat()

2.6754061904790403 2.6754062 2.6754062 2.6754062175750732 2.6754062175750732
5
[1.12682361 1.32971843 1.35466786 1.93095382 1.56567645] 
 [1.1268235 1.3297185 1.3546679 1.9309537 1.5656765] 
 [1.1268235 1.3297185 1.3546679 1.9309537 1.5656765] 

