In [1]:
'''notebook to check if our matrices yield the correct results'''

from pbmo.lib.pymatrix import pyMatrix, npMatrix, cpMatrix
from pbmo.lib._libpbmo import Matrix, BoostMatrix
import numpy as np

In [5]:
# initalize
arr = np.random.rand(5, 5).astype(np.float32)

pymatrix = pyMatrix(arr)
npmatrix = npMatrix(arr)
cpmatrix = cpMatrix(arr)
cppmatrix = Matrix(arr)
boostmatrix = BoostMatrix(arr)

# check norm values
print(pymatrix.norm(), npmatrix.norm(), cpmatrix.norm(), cppmatrix.norm(), boostmatrix.norm())

# check matrix multiplication values
arr1 = np.random.rand(5, 5).astype(np.float32)

pymatrix1 = pyMatrix(arr1)
npmatrix1 = npMatrix(arr1)
cpmatrix1 = cpMatrix(arr1)
cppmatrix1 = Matrix(arr1)
boostmatrix1 = BoostMatrix(arr1)

# boostmatrix1.print_mat()

ans = cppmatrix.matmul(cppmatrix1, True)
print(ans)
# print(result_cpp.rows)
ans2 = boostmatrix.matmul(boostmatrix1, True)
# print(result_boost.rows)
print(ans2)

print(
    pymatrix.matmul(pymatrix1).arr,
    "\n",
    npmatrix.matmul(npmatrix1).arr,
    "\n",
    cpmatrix.matmul(cpmatrix1).arr,
    "\n"
)

# cppmatrix.matmul(cppmatrix1).print_mat()
# boostmatrix.matmul(boostmatrix1).print_mat()

2.901497520891767 2.9014976 2.9014976 2.9014976024627686 2.9014976024627686
(<pbmo.lib._libpbmo.Matrix object at 0x000002247EDF0F10>, 9.999999974752427e-07)
(<pbmo.lib._libpbmo.BoostMatrix object at 0x000002247EDF0F80>, 6.000000212225132e-07)
[[1.38564931 1.50194268 1.00151515 1.0222236  1.08665376]
 [2.32048675 2.43517195 1.5582054  1.75586773 1.58150007]
 [2.5721615  2.56455883 1.62615602 1.77871136 1.81131047]
 [1.23554696 1.15206337 0.83215763 1.1735391  0.84672303]
 [1.5227918  1.3640197  0.69707405 0.76754354 1.05305921]] 
 [[1.3856493  1.5019426  1.0015152  1.0222236  1.0866537 ]
 [2.3204868  2.4351718  1.5582054  1.7558677  1.5815    ]
 [2.5721614  2.5645587  1.6261561  1.7787114  1.8113105 ]
 [1.235547   1.1520634  0.8321577  1.173539   0.846723  ]
 [1.5227917  1.3640198  0.697074   0.76754355 1.0530592 ]] 
 [[1.3856493  1.5019426  1.0015152  1.0222236  1.0866537 ]
 [2.3204868  2.435172   1.5582054  1.7558677  1.5815    ]
 [2.5721614  2.564559   1.6261561  1.7787114  1.8113105