In [1]:
'''notebook to check if our matrices yield the correct results'''

from pbmo.lib.pymatrix import pyMatrix, npMatrix, cpMatrix
from pbmo.lib._libpbmo import Matrix, BoostMatrix
import numpy as np

In [2]:
# initalize
arr = np.random.rand(5, 5).astype(np.float32)

pymatrix = pyMatrix(arr)
npmatrix = npMatrix(arr)
cpmatrix = cpMatrix(arr)
cppmatrix = Matrix(arr)
boostmatrix = BoostMatrix(arr)

# check norm values
print(pymatrix.norm(), npmatrix.norm(), cpmatrix.norm(), cppmatrix.norm(), boostmatrix.norm())

# check matrix multiplication values
arr1 = np.random.rand(5, 5).astype(np.float32)

pymatrix1 = pyMatrix(arr1)
npmatrix1 = npMatrix(arr1)
cpmatrix1 = cpMatrix(arr1)
cppmatrix1 = Matrix(arr1)
boostmatrix1 = BoostMatrix(arr1)

# boostmatrix1.print_mat()

ans = cppmatrix.matmul(cppmatrix1, True)
print(ans)
# print(result_cpp.rows)
ans2 = boostmatrix.matmul(boostmatrix1, True)
# print(result_boost.rows)
print(ans2)

print(
    pymatrix.matmul(pymatrix1).arr,
    "\n",
    npmatrix.matmul(npmatrix1).arr,
    "\n",
    cpmatrix.matmul(cpmatrix1).arr,
    "\n"
)

# cppmatrix.matmul(cppmatrix1).print_mat()
# boostmatrix.matmul(boostmatrix1).print_mat()

2.656661149604369 2.656661 2.656661 2.656661033630371 2.656661033630371
(<pbmo.lib._libpbmo.Matrix object at 0x000001AFA4F94470>, 3.000000106112566e-07)
(<pbmo.lib._libpbmo.BoostMatrix object at 0x000001AFA4F944F0>, 3.000000106112566e-07)
[[1.93615801 1.37579574 0.72943056 1.35995575 1.70596467]
 [1.75675014 1.39902953 0.95424068 1.44503529 1.32013582]
 [0.51088119 0.52009358 0.2848688  0.44868553 0.34826628]
 [2.27027026 1.84333537 1.25292702 1.50391801 1.47616666]
 [1.45133903 1.36123033 1.23541826 1.33074284 0.70696194]] 
 [[1.9361581  1.3757958  0.72943056 1.3599557  1.7059647 ]
 [1.7567502  1.3990295  0.9542407  1.4450353  1.3201358 ]
 [0.5108812  0.52009356 0.2848688  0.44868553 0.34826627]
 [2.27027    1.8433354  1.2529271  1.5039179  1.4761667 ]
 [1.451339   1.3612304  1.2354183  1.3307428  0.7069619 ]] 
 [[1.9361581  1.3757958  0.72943056 1.3599557  1.7059647 ]
 [1.7567501  1.3990295  0.9542407  1.4450353  1.3201358 ]
 [0.5108812  0.52009356 0.2848688  0.44868556 0.34826627]
 